Stockit/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('inventory/', include("inventory.urls")),
    path('users/', include("users.urls")),
]

home/urls.py
from django.urls import path
from . import views

app_name = "home"

urlpatterns = [
    path('', views.HomeView.as_view(), name="home"),
    path('about/', views.AboutView.as_view(), name="about"),
]

inventory/urls.py
from django.urls import path
from . import views

app_name = "inventory"

urlpatterns = [
    path('', views.ItemList.as_view(), name="item_list"),
    path('new/', views.ItemCreate.as_view(), name="item_create"),
    path('<int:pk>/', views.ItemDetail.as_view(), name="item_detail"),
    path('<int:pk>/update/', views.ItemUpdate.as_view(), name="item_update"),
    path('<int:pk>/delete/', views.ItemDelete.as_view(), name="item_delete"),
    path('types/', views.ItemTypeList.as_view(), name="itemtype_list"),
    path('types/new/', views.ItemTypeCreate.as_view(), name="itemtype_create"),
    path('types/<int:pk>/update/', views.ItemTypeUpdate.as_view(), name="itemtype_update"),
    path('types/<int:pk>/delete/', views.ItemTypeDelete.as_view(), name="itemtype_delete"),
]

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "users"

urlpatterns = [
    path("", views.UserList.as_view(), name="list"),
    path("<int:pk>/", views.UserDetail.as_view(), name="detail"),
    path("<int:pk>/update/", views.UserUpdate.as_view(), name="update"),
    path("<int:pk>/delete/", views.UserDelete.as_view(), name="delete"),
    path("register/", views.UserCreate.as_view(), name="register"),
    path("login/", auth_views.LoginView.as_view(template_name="users/login.html"), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
]

home/models.py
from django.db import models

# Create your models here.

inventory/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse

# Create your models here.
class ItemType(models.Model):
    name = models.CharField(max_length=45, null=False, unique=True)

    def __str__(self):
        return f"ID {self.id}: {self.name}"
    
    def get_absolute_url(self):
        return reverse("inventory:itemtype_list")

    class Meta:
        verbose_name_plural = "Item Types"


class Item(models.Model):
    name = models.CharField(max_length=45, null=False)
    weight = models.DecimalField(max_digits=5, decimal_places=2, null=False)
    price = models.DecimalField(max_digits=7, decimal_places=2, null=False, default=0)
    description = models.CharField(max_length=45)
    quantity = models.IntegerField(null=False, default=0)
    itemtype = models.ForeignKey(ItemType, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return f"ID {self.id}: {self.name} (${self.price})"

    def get_absolute_url(self):
        return reverse("inventory:item_detail", args=(self.id,))

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.urls import reverse

# Create your models here.
class User(AbstractUser):
    phone_number = models.CharField(max_length=45, null=False)
    street_address = models.CharField(max_length=45, null=False)
    city = models.CharField(max_length=45, null=False)
    state = models.CharField(max_length=25, null=True)
    zipcode = models.CharField(max_length=5, null=True)


    @property
    def name(self):
        return self.first_name + " " + self.last_name
    
    @property
    def address(self):
        return self.street_address + ", " + self.city + ", " + self.state + " " + self.zipcode

    def get_absolute_url(self):
        return reverse("home:home")

inventory/forms.py
from django import forms
from .models import Item, ItemType

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = "__all__"


class ItemTypeForm(forms.ModelForm):
    class Meta:
        model = ItemType
        fields = "__all__"

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from .models import User

class UserCreateForm(UserCreationForm):
    class Meta:
        model = User
        exclude = ["last_login", "is_superuser", "is_active", "is_staff", "groups", "user_permissions", "date_joined", "password"]


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ["username", "first_name", "last_name", "email", "phone_number", "street_address", "city", "state", "zipcode"]

home/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView

# Create your views here.
class HomeView(TemplateView):
    template_name = "index.html"

class AboutView(TemplateView):
    template_name = "about.html"

inventory/views.py
from django.shortcuts import render
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse_lazy
from .models import Item, ItemType
from .forms import ItemForm, ItemTypeForm

# Create your views here.
class ItemList(ListView):
    template_name = "items/list.html"
    model = Item
    context_object_name = "items"


class ItemDetail(DetailView):
    template_name = "items/detail.html"
    model = Item
    context_object_name = "item"


class ItemCreate(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    template_name = "items/new_or_update.html"
    model = Item
    form_class = ItemForm

    def test_func(self):
        return self.request.user.is_superuser or self.request.user.is_staff


class ItemUpdate(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    template_name = "items/new_or_update.html"
    model = Item
    form_class = ItemForm

    def test_func(self):
        return self.request.user.is_superuser or self.request.user.is_staff


class ItemDelete(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    template_name = "items/delete.html"
    model = Item
    success_url = reverse_lazy("inventory:item_list")

    def test_func(self):
        return self.request.user.is_superuser or self.request.user.is_staff


class ItemTypeList(LoginRequiredMixin, UserPassesTestMixin, ListView):
    template_name = "itemtypes/list.html"
    model = ItemType
    context_object_name = "itemtypes"

    def test_func(self):
        return self.request.user.is_superuser or self.request.user.is_staff


class ItemTypeCreate(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    template_name = "itemtypes/new_or_update.html"
    model = ItemType
    form_class = ItemTypeForm

    def test_func(self):
        return self.request.user.is_superuser or self.request.user.is_staff


class ItemTypeUpdate(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    template_name = "itemtypes/new_or_update.html"
    model = ItemType
    form_class = ItemTypeForm

    def test_func(self):
        return self.request.user.is_superuser or self.request.user.is_staff


class ItemTypeDelete(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    template_name = "itemtypes/delete.html"
    model = ItemType
    success_url = reverse_lazy("inventory:itemtype_list")

    def test_func(self):
        return self.request.user.is_superuser or self.request.user.is_staff

users/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from .models import User
from .forms import UserCreateForm, UserUpdateForm

# Create your views here.
class UserList(ListView):
    template_name = "users/list.html"
    model = User
    queryset = User.objects.filter(is_active=True)
    context_object_name = "users"


class UserDetail(DetailView):
    template_name = "users/detail.html"
    model = User
    context_object_name = "user_"


class UserCreate(CreateView):
    template_name = "users/register.html"
    model = User
    form_class = UserCreateForm


class UserUpdate(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = User
    template_name = "users/update.html"
    form_class = UserUpdateForm

    def test_func(self):
        return self.request.user.is_superuser or (self.request.user == self.get_object())


class UserDelete(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = User
    template_name = "users/delete.html"

    def test_func(self):
        return self.request.user.is_superuser or (self.request.user == self.get_object())

    def delete(self, request, *args, **kwargs):
        user_ = self.get_object()
        user_.is_active = False
        user_.save()
        return redirect("users:list")

home/templates/about.html
{% extends "base.html" %}

{% block content %}
    <h1>About Page</h1>

    <p>
        StockIt is an inventory application specifically used for Wholesale Food markets. 
        This app will help employees regulate inventory checks faster and quicker or even times safer. 
        Many wholesale food markets may not have up to date technology and require manual labor.
    </p>
{% endblock content %}

home/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>Stockit</title>
        <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    </head>
    <body>
        <a href="{% url 'home:home' %}">Stockit</a>
        {% if user.is_authenticated %}
            <a href="{% url 'users:logout' %}">Logout</a>
            <a href="{% url 'users:detail' user.id %}"><b>Hi, {{ user.first_name }}!</b></a>
        {% else %}
            <a href="{% url 'users:login' %}">Login</a>
            <a href="{% url 'users:register' %}">Register</a>
        {% endif %}
        {% block content %}{% endblock content %}
    </body>
</html>

home/templates/confirm_delete.html
{% extends "base.html" %}

{% block content %}
    <form method="POST">
        {% csrf_token %}
        <h3>Are you sure you want to delete "{{ object }}"?</h3>
        <button type="submit">Delete</button>
    </form>

    {% block back_button %}{% endblock back_button %}
{% endblock content %}

home/templates/form.html
{% extends "base.html" %}

{% block content %}
    <form enctype="multipart/form-data" method="POST" class="form-horizontal">
        {% csrf_token %}
        <div class="form-group">
            {{ form.as_p }}
        </div>
        <button type="submit">Submit</button>
    </form>

    {% block back_button %}{% endblock back_button %}
{% endblock content %}

home/templates/index.html
{% extends "base.html" %}

{% block content %}
    <h1>Welcome to Stockit!</h1>
    <a href="{% url 'home:about' %}">About Us</a>

    <a href="{% url 'inventory:item_list' %}">Browse</a>
    <a href="{% url 'users:list' %}">User Accounts</a>
{% endblock content %}

inventory/templates/items/delete.html
{% extends "confirm_delete.html" %}

{% block back_button %}
    <a href="{% url 'inventory:item_detail' item.id %}">Back</a>
{% endblock back_button %}

inventory/templates/items/detail.html
{% extends "base.html" %}

{% block content %}
    <ul>
        <li><b>ID:</b> {{ item.id }}</li>
        <li><b>Name:</b> {{ item.name }}</li>
        <li><b>Weight:</b> {{ item.weight }}</li>
        <li><b>Price:</b> ${{ item.price }}</li>
        <li><b>Description:</b> {{ item.description }}</li>
        <li><b>Quantity:</b> {{ item.quantity }}</li>
        <li><b>Item Type:</b> {{ item.itemtype.name }}</li>
    </ul>
    <a href="{% url 'inventory:item_list' %}">Back</a>
    
    {% if user.is_superuser or user.is_staff %}
        <td><a href="{% url 'inventory:item_update' item.id %}">Update</a></td>
        <td><a href="{% url 'inventory:item_delete' item.id %}">Delete</a></td>
    {% endif %}
{% endblock content%}

inventory/templates/items/list.html
{% extends "base.html" %}

{% block content %}
    {% if user.is_superuser or user.is_staff %}
        <a href="{% url 'inventory:item_create' %}">Add Item</a>
        <a href="{% url 'inventory:itemtype_list' %}">View Types</a>
    {% endif %}
    <table>
        <thead>
            <tr>
                <td>ID</td>
                <td>Name</td>
                <td>Item Type</td>
                <td>Stock</td>
                <td>Price</td>
                <td colspan="3">Options</td>
            </tr>
        </thead>
        <tbody>
            {% for item in items %}
            <tr>
                <td>{{ item.id }}</td>
                <td>{{ item.name }}</td>
                <td>{{ item.itemtype.name }}</td>
                <td>{{ item.quantity }}</td>
                <td>${{ item.price }}</td>
                <td><a href="{% url 'inventory:item_detail' item.id %}">View</a></td>
                
                {% if user.is_superuser or user.is_staff %}
                    <td><a href="{% url 'inventory:item_update' item.id %}">Update</a></td>
                    <td><a href="{% url 'inventory:item_delete' item.id %}">Delete</a></td>
                {% endif %}
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content%}

inventory/templates/items/new_or_update.html
{% extends "form.html" %}

{% block back_button %}
    <a href="{% url 'inventory:item_list' %}">Back</a>
{% endblock back_button %}

inventory/templates/itemtypes/delete.html
{% extends "confirm_delete.html" %}

{% block back_button %}
    <a href="{% url 'inventory:itemtype_list' %}">Back</a>
{% endblock back_button %}

inventory/templates/itemtypes/list.html
{% extends "base.html" %}

{% block content %}
    {% if user.is_superuser%}
        <a href="{% url 'inventory:itemtype_create' %}">Add Item Type</a>
    {% endif %}

    <a href="{% url 'inventory:item_list' %}">View Inventory</a>
    <table>
        <thead>
            <tr>
                <td>ID</td>
                <td>Name</td>
                <td colspan="3">Options</td>
            </tr>
        </thead>
        <tbody>
            {% for itemtype in itemtypes %}
            <tr>
                <td>{{ itemtype.id }}</td>
                <td>{{ itemtype.name }}</td>
                
                {% if user.is_superuser %}
                    <td><a href="{% url 'inventory:itemtype_update' itemtype.id %}">Update</a></td>
                    <td><a href="{% url 'inventory:itemtype_delete' itemtype.id %}">Delete</a></td>
                {% endif %}
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content%}

inventory/templates/itemtypes/new_or_update.html
{% extends "form.html" %}

{% block back_button %}
    <a href="{% url 'inventory:itemtype_list' %}">Back</a>
{% endblock back_button %}

users/templates/users/delete.html
{% extends 'confirm_delete.html' %}

{% block back_button %}
    <a href="{% url 'users:detail' user.id %}">Back</a>
{% endblock back_button%}

users/templates/users/detail.html
{% extends "base.html" %}

{% block content %}
    <ul>
        <li><b>ID:</b> {{ user_.id }}</li>
        <li><b>Username:</b> {{ user_.username }}</li>
        <li><b>Name:</b> {{ user_.name }}</li>
        <li><b>Phone Number:</b> {{ user_.phone_number }}</li>
        <li><b>Email:</b> {{ user_.email }}</li>
        {% if user.is_superuser or user.is_staff or user == user_ %}
            <li><b>Address:</b> {{ user_.address }}</li>
        {% endif %}
        <li><b>Administrator:</b> {{ user_.is_superuser|yesno:"Yes,No" }}</li>
    </ul>
    
    <a href="{% url 'users:list' %}">Back</a>

    {% if user.is_superuser or user == user_ %}
        <a href="{% url 'users:update' user_.id %}">Update</a>
        <a href="{% url 'users:delete' user_.id %}">Delete</a>
    {% endif %}
{% endblock content%}

users/templates/users/list.html
{% extends "base.html" %}

{% block content %}
    <table>
        <thead>
            <tr>
                <td>ID</td>
                <td>Name</td>
                <td>Phone</td>
                <td>Email</td>
                {% if user.is_superuser or user.is_staff %}
                    <td>Address</td>
                {% endif %}
                <td>Administrator</td>
                <td>Staff</td>
                <td colspan="3">Options</td>
            </tr>
        </thead>
        <tbody>
            {% for user_ in users %}
            <tr>
                <td>{{ user_.id }}</td>
                <td>{{ user_.name }}</td>
                <td>{{ user_.phone_number }}</td>
                <td>{{ user_.email }}</td>
                {% if user.is_superuser or user.is_staff %}
                    <td>{{ user_.address }}</td>
                {% endif %}
                <td>{{ user_.is_superuser|yesno:"Yes,No" }}</td>
                <td>{{ user_.is_staff|yesno:"Yes,No" }}</td>
                <td><a href="{% url 'users:detail' user_.id %}">View</a></td>
                
                {% if user.is_superuser or user == user_ %}
                    <td><a href="{% url 'users:update' user_.id %}">Update</a></td>
                    <td><a href="{% url 'users:delete' user_.id %}">Delete</a></td>
                {% endif %}
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content%}

users/templates/users/login.html
{% extends 'form.html' %}

{% block back_button %}
    <a href="{% url 'home:home' %}">Back</a>
{% endblock back_button %}

users/templates/users/register.html
{% extends 'form.html' %}

{% block back_button %}
    <a href="{% url 'home:home' %}">Back</a>
{% endblock back_button %}

users/templates/users/update.html
{% extends 'form.html' %}

{% block back_button %}
    <a href="{% url 'users:detail' user.id %}">Back</a>
{% endblock back_button %}